# Generated by Django 4.2.2 on 2024-02-18 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_archivo_imagen_texto_contenido_articulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='Titulo',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='contenido',
            old_name='Imagen',
            new_name='imagen',
        ),
    ]
